// Code generated by error-gen. DO NOT EDIT.

package generr

import (
	"apierr"
	"fmt"
)

const (
	ErrorNotFound = "NotFound" // Resource not found error.
	

	// Error Types
	ErrTypeERR_NOT_FOUND = "ERR_NOT_FOUND"

	// Error Codes
	ErrCodeNOT_FOUND = "NOT_FOUND"
)


// NotFoundError represents Resource not found error..
type NotFoundError struct {
	apierr.CustomError
	resource string
}

// NewNotFoundError creates a new NotFoundError.
func NewNotFoundError(
	resource string,
) *apierr.CustomError {
	return apierr.New(
		404,
		fmt.Sprintf(
			"%s not found",
			resource, 
		),
		"The resource you requested does not exist.",
		"ERR_NOT_FOUND",	
		"NOT_FOUND",
	)
}

